# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_tile.proto

require 'google/protobuf'


descriptor_data = "\n\x11vector_tile.proto\"\xf2\x03\n\x04Tile\x12\x1b\n\x06layers\x18\x03 \x03(\x0b\x32\x0b.Tile.Layer\x1a\x97\x01\n\x05Value\x12\x14\n\x0cstring_value\x18\x01 \x01(\t\x12\x13\n\x0b\x66loat_value\x18\x02 \x01(\x02\x12\x14\n\x0c\x64ouble_value\x18\x03 \x01(\x01\x12\x11\n\tint_value\x18\x04 \x01(\x03\x12\x12\n\nuint_value\x18\x05 \x01(\x04\x12\x12\n\nsint_value\x18\x06 \x01(\x12\x12\x12\n\nbool_value\x18\x07 \x01(\x08\x1a\x64\n\x07\x46\x65\x61ture\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x04tags\x18\x02 \x03(\rB\x02\x10\x01\x12%\n\x04type\x18\x03 \x01(\x0e\x32\x0e.Tile.GeomType:\x07UNKNOWN\x12\x14\n\x08geometry\x18\x04 \x03(\rB\x02\x10\x01\x1a\x8b\x01\n\x05Layer\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x1f\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\r.Tile.Feature\x12\x0c\n\x04keys\x18\x03 \x03(\t\x12\x1b\n\x06values\x18\x04 \x03(\x0b\x32\x0b.Tile.Value\x12\x12\n\x07version\x18\x05 \x02(\r:\x01\x31\x12\x14\n\x06\x65xtent\x18\x06 \x01(\r:\x04\x34\x30\x39\x36\"?\n\x08GeomType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05POINT\x10\x01\x12\x0e\n\nLINESTRING\x10\x02\x12\x0b\n\x07POLYGON\x10\x03\x42\r\xea\x02\nVectorTile"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module VectorTile
  Tile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tile").msgclass
  Tile::Value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tile.Value").msgclass
  Tile::Feature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tile.Feature").msgclass
  Tile::Layer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tile.Layer").msgclass
  Tile::GeomType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tile.GeomType").enummodule
end
